= mason-play

Experiments with MASON - trying to get it to work without a main class


The flow of of a simulation request should be

1. User signs in
2. User picks a species, optionally change some of the species parameters, and enters metadata required to run the sim.
3. The sends a post to endpoints.DataInput
4. DataInput puts it in a queue (or perhaps a POST) for SimManager ( a separate microservice) to pick up

4. SimManager grabs the job off the queue or gets the POST
5. SimManager creates a queue of number of sims to run divided by some factor
6. SimManager Creates as many SimRunners as it wants to speed up the processing. Each simrunner populated with the right info
6. SimRunner then runs the simulation

== Input and Output Grid
The input grid for "habitat" must be projected but we don't care which projection

We will compute pixel size by Xmax-Xmin and Ymax-Ymin (pixel size need to be the same in both directions)

The output grid will cover the same extent and pixel size as the habitat grid

== Animals on a rasterized or continuous surface
There is no reason why the animals can't actually move in continual space and just query the raster under them
I need to bounc that idea off someone


Since MASON and GeoMason are not in a Maven repository we either need to

1. Put them in our own repository and reference that in this maven pom.
Here is the https://azure.microsoft.com/en-us/products/devops/artifacts[Azure Product] that should do this

2. Install the jar files to the local maven repository for any machine build our project

Option 2 looks like this (found on https://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-to-a-maven-project[stack overflow]

    mvn install:install-file \
    -Dfile=<path-to-file> \
    -DgroupId=<group-id> \
    -DartifactId=<artifact-id> \
    -Dversion=<version> \
    -Dpackaging=<packaging> \
    -DgeneratePom=true

Where each refers to:

`<path-to-file>`: the path to the file to load e.g → `c:\kaptcha-2.3.jar`

`<group-id>`: the group that the file should be registered under e.g → `com.google.code`

`<artifact-id>`: the artifact name for the file e.g → `kaptcha`

`<version>`: the version of the file e.g → `2.3`

`<packaging>`: the packaging of the file e.g. → `jar`

```
 mvn install:install-file -Dfile="ext-jars\mason.21.jar" -DgroupId="org.mason" -DartifactId="masonRelease" -Dversion="21" -Dpackaging=jar

```

**Reference**

* Maven FAQ: [I have a jar that I want to put into my local repository. How can I copy it in?][1]
* Maven Install Plugin Usage: [The `install:install-file` goal][2]

[1]: http://maven.apache.org/general.html#importing-jars
[2]: https://maven.apache.org/plugins/maven-install-plugin/usage.html#The_install:install-file_goal